### ISSUE TITLE
Correct responsiveness of web site.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/lbl-tribute-page#6]
- There is a lot of space between sections in the mobile view.
- On certain laptop screens, the items overlap each other a little.

**Comment by jydoskey** [comment]
Hello HarshKapadia2, I will like to help fix the issues with the responsiveness of your website.

**Comment by HarshKapadia2** [comment]
Hey @jydoskey I am adding some content in a bit and those will be the final additions.
I would suggest that you should go for this issue after that, so that my changes will not affect yours.

I'll drop a comment here after I'm done with the changes. Is that fine with you?

**Comment by jydoskey** [comment]
Thanks, that's fine by me.

**Comment by HarshKapadia2** [comment]
Hey @jydoskey, I have made all the changes that I wanted to make.
You can go ahead and try to solve the issues in this repo!

PS: If you have already forked this repo previously, please delete your fork and fork this repo again to have the latest changes.

**Comment by jydoskey** [comment]
Will fork the repo again and update what I have. Thanks

**Comment by HarshKapadia2** [comment]
No problem!
I have assigned you to this issue!
